# Generated by Django 6.0.3 on 2026-07-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('CNG', 'CNG')], max_length=50)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'CVT')], max_length=50)),
                ('mileage', models.DecimalField(decimal_places=2, help_text='kmpl or km/kWh', max_digits=6)),
                ('seating_capacity', models.IntegerField(default=5)),
                ('engine_cc', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=2, help_text='bhp', max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, upload_to='cars/')),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
