# Generated by Django 6.0.3 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Crossover', 'Crossover'), ('Pickup', 'Pickup'), ('Van', 'Van')], default='Sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='safety_rating',
            field=models.IntegerField(default=3, help_text='Safety rating 1-5'),
        ),
    ]
