# Generated by Django 6.0.3 on 2026-07-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_convert_prices_to_inr'),
    ]

    operations = [
    ]
