# Generated by Django 6.0.3 on 2026-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_body_type',
            field=models.CharField(blank=True, help_text='SUV, Sedan, Hatchback, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='safety_priority',
            field=models.IntegerField(blank=True, help_text='Minimum safety rating 1-5', null=True),
        ),
    ]
